### ISSUE TITLE
Add changelog automatic generation

### ISSUE THREAD

**Issue by abonas** [abonas/kubeclient#112]

**Comment by abonas** [comment]
based on this https://github.com/skywinder/Github-Changelog-Generator

**Comment by simon3z** [comment]
> based on this https://github.com/skywinder/Github-Changelog-Generator

I feel that it should be integrated with rake and we should document/automate the release procedure (so that we won't forget about generating it).

**Comment by abonas** [comment]
> I feel that it should be integrated with rake and we should document/automate the release procedure (so that we won't forget about generating it).

I agree with you it should be integrated with rake. the only issue here which I don't have a good solution for at the moment, is that like version.rb, it is modified and commited locally, so if it's generated when doing 'rake build' or 'rake release' - it's too late.

**Comment by cben** [comment]
I've tried using this generator now and the results are bad (though long and impressive):
https://github.com/cben/kubeclient/blob/github_changelog_generator/CHANGELOG.md

- PRs are mis-attributed to wrong release!
  eg. it put "Support ruby 2.4 #247 (cben)" under v2.4.0, but it is NOT in that release.
  I suspect assumes linear history and looks at *time* PR was merged ignoring which branch it landed on??
- "Closed issues:" section is a nice attempt, but doesn't mean much.  Not sure how it works but probably by time of closure?
- Signal/noise is too low.  I agree with keepachangelog.com the whole point of a changelog is human-curated summary; if one wants the raw data, just browse github — especially since 

I'm now manually writing a correct log for last release or two and my opinion is it doesn't help even as a base for manual editing.
Closing this, feel free to reopen if you see an automatic solution that actually helps.
What does help (with  false positives for unclean picks — they appear on both sides) is [git cherry](https://git-scm.com/docs/git-cherry):
```
$ git cherry -v v2.5.1 origin/master
$ git cherry -v origin/master v2.5.1 
```
