### ISSUE TITLE
return hashes instead of RecursiveObjectStruct

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#197]
less magic ... less work/coversion ... more performance ?
... sounds good ? ... maybe optional via config ?

**Comment by simon3z** [comment]
cc @moolitayer

**Comment by moolitayer** [comment]
This would be at most an optional (global instance config value that we would need to add) optimization (over to_h). I'm not sure if it is worth the trouble. if we go down this path we should consider input/output together.

**Comment by jrafanie** [comment]
> maybe optional via config ?

I'd imagine that would be hard because you'd have to support both configurations, dot notation and hash access...  Either way, if the performance is that awful, maybe we have no choice but use the simplest solution using hashes... although @moolitayer brings up a great point to consider how we're requesting data and parsing it.  If we can request it json or another format that's faster or uses significantly less memory or both, we should consider that path.

**Comment by moolitayer** [comment]
See https://github.com/abonas/kubeclient/pull/262, add option for raw and avoids ROS (and JSON parsing altogether)

**Comment by cben** [comment]
I think your #306 `as: :parsed` & `as: :parsed_symbolized` covers this.  Can this be closed?
