### ISSUE TITLE
how to enable verbose logging?

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [abonas/kubeclient#310]
Is there some way to enable verbose logging to see the URLs being generated along with
responses?

**Comment by cben** [comment]
Simplest is using RestClient's builtin logging:
https://stackoverflow.com/questions/23463465/how-to-debug-display-request-sent-using-restclient
This will not cover watch connections because these use http gem rather
than rest-client.

You can also try httplog gem: https://github.com/trusche/httplog (it does
monkey-patching, so must to required after kubeclient).
This should cover both (it doesnt have a specific rest-client adapter but
it covers Net::HTTP which rest-client uses).

**Comment by Eric-Fontana-Bose** [comment]
Thanks will do

**Comment by cben** [comment]
Closing, feel free to reopen or open a new one if you have more questions.
