### ISSUE TITLE
Support json patch & json merge patch in addition to strategic patch

### ISSUE THREAD

**Issue by Stono** [abonas/kubeclient#357]
`Error message: the body of the request was in an unknown format - accepted media types include: application/json-patch+json,application/merge-patch+json`

Using 

`@atcloud.patch_service_check(check.metadata.name, {metadata: {annotations: {key: 'value'}}}, check.metadata.namespace)`

Any ideas?

**Comment by Stono** [comment]
This monkeypatch resolved it:
```
module Kubeclient
  module ClientMixin
    def patch_entity(resource_name, name, patch, namespace = nil)
      ns_prefix = build_namespace_prefix(namespace)
      response = handle_exception do
        rest_client[ns_prefix + resource_name + "/#{name}"]
          .patch(
            patch.to_json,
            { 'Content-Type' => 'application/merge-patch+json' }.merge(@headers)
          )
      end
      format_response(@as, response.body)
    end
  end 
end 
```

K8 1.10.7

**Comment by cben** [comment]
Is that a custom resource (CRD)?
per https://github.com/kubernetes/kubernetes/issues/58414, strategic merge patch (which is what kubeclient currently sends) for CRDs is unsupported and not planned.

Your change above redefines `patch_*` methods to take a different format, this isn't backward compatible, I don't think we can do that in kubeclient.

But we clearly need to add a way to choose patch format.
An additional param?  Would have to be optional, default to strategic.
Separate methods for each format?  Say add `json_patch_*` and `merge_patch_*` in addition to `patch_*` (and document `patch_*` doesn't always work).
I prefer separate methods, as the signature is simpler — each method takes a fixed "type" rather than overloaded based on another arg.  Plus less mental pressure to use the suboptimal "default".

What do you think?

PS. doc on the formats: https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

**Comment by Stono** [comment]
Hey @cben - yes this is a patch against a CRD so that makes sense indeed and I agree with you, well named functions for the purpose over an expanding list of arguments.

**Comment by cben** [comment]
I'll be happy to take a PR.  Otherwise, I'm unlikely to get to this any time soon, I need to focus on bugs first (especially #318).
