### ISSUE TITLE
jsonpath dependency incorrectly listed

### ISSUE THREAD

**Issue by Donald47** [abonas/kubeclient#444]
jsonpath is listed as a development dependency https://github.com/abonas/kubeclient/blob/cab82dbefd51d26d2399469a5a3357a3e98df0f1/kubeclient.gemspec#L33
but is directly called by
https://github.com/abonas/kubeclient/blob/cab82dbefd51d26d2399469a5a3357a3e98df0f1/lib/kubeclient/gcp_command_credentials.rb#L27

This seems like a mistake?

**Comment by cben** [comment]
Thanks for noticing!
This was _maybe_ intentional but if so must be documented (?)
We started a pattern of making some large auth provider dependencies — specifically `googleauth` and `aws-sigv4` — "optional" by NOT declaring them as normal dependencies.  We (1) explained in README you need to depend on them yourself if you want that functionality, (2) wrapped LoadError for them in an exception explaining it clearly (3) added as dev dependencies only for tests.

We _could_ do the same for jsonpath.  But it's pretty small: +79kB plus dependencies `multi_json` +72kB and `to_regexp` +31kB, together they increase bundle size by less than 1%.
@lucasmazza what do you think?  Promote to regular dependency?

**Comment by cben** [comment]
Above numbers were from `bundle install --without development --path vendor/bundle`, and ignoring `cache` directory, only `gems`.  With `bundle install --deployment` I see a larger difference for some reason :shrug: 34.4MB -> 34.8MB, total increase 420kB, ~1.2%.  Anyway negligible compared to other stuff.
