### ISSUE TITLE
inline ClientMixin

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#492]
this always seems like a weird architecture to me, I'd propose to get rid of it and whichever gems used to mix it in can just change to not do that

/cc @cben

**Comment by cben** [comment]
Yep, good idea.
The original motivation was for `openshift_client` gem, which is long unnecessary and unmaintained (https://github.com/abonas/openshift_client/pull/31).

**Comment by cben** [comment]
Searched github for mentions of ClientMixin (not because I have concerns in this case, I just enjoy this aspect of open source that I _can_ get a good sample of depenent code).
Most are simply vendored copies of kubeclient.

- https://github.com/pokka/samson-gitlab/blob/f8db95c35d6b625516011a760d026feb5ae92c2b/plugins/kubernetes/config/initializers/watchers.rb monkey-patches some ancient kubeclient version — before discovery was a thing.  If they update to a recent version this file becomes unnecessary.
- https://github.com/taejune/3scale-porta/blob/732944bcd525191a61a9607a4b572fbc67debe1f/test/test_helpers/service_discovery.rb#L19 calls `ClientMixin.resource_class`, dropped in 3.0.
- https://github.com/zanloy/bms/blob/2c6238c01636f4d0d7174ce65a1c7579a34d5177/connectors/kubectl.rb is a new class that includes ClientMixin.  Could simply include Client instead.
- https://github.com/zanloy/bms/blob/2c6238c01636f4d0d7174ce65a1c7579a34d5177/connectors/kubectl.rb adds several new methods (superset of #422).  Could patch Client instead?
- https://github.com/zendesk/samson/blob/d3a1de89e79e062681685154b74b5f0e76628755/plugins/kubernetes/app/models/kubernetes/resource.rb#L233 calls `ClientMixin.underscore_entity`.  @grosser that's your code :-)  
  Can you call it through `Client` today?    Hmm, that doesn't work.  Apparently ruby `include` does not inherit class methods.   :disappointed:

  BTW, `underscore_entity` is not public, and isn't reliable for predicting generated method names (pluralization, `resolve_unconventional_method_names`...)  What's missing from kubeclient to achieve what you do there?  probably #332?
